apiVersion: batch/v1
kind: Job
metadata:
  name: flink-job-submit-learning
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job-submitter
          image: pratulw5/frauddetection-flinkjobs:dev
          imagePullPolicy: "Always"
          command:
            [
              "bash", "-c",
              "echo 'Waiting for JobManager REST on port 8081...'; \
              while ! (echo > /dev/tcp/flink-jobmanager/8081) 2>/dev/null; do sleep 2; done; \
              echo 'Submitting job...'; \
              flink run -d -m flink-jobmanager:8081 -py /opt/Jobs/Combine.py"
            ]

