apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    component: taskmanager
spec:
  ports:
    - port: 6121  # Flink TaskManager RPC
      targetPort: 6121
  selector:
    app: flink
    component: taskmanager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 1  # You can scale this based on your resource requirements
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: pratulw5/frauddetection-flink:dev  
          ports:
            - containerPort: 6121  # Flink TaskManager RPC
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager"
          command: ["/docker-entrypoint.sh"]
          args: ["taskmanager"]
