apiVersion: batch/v1
kind: Job
metadata:
  name: flink-submit-after-kafka-topics
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: kafka-create-topics
          image: bitnami/kafka:3.7.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Creating Kafka topic: raw-transactions"
              kafka-topics.sh \
                --create \
                --topic raw-transactions \
                --partitions 1 \
                --replication-factor 1 \
                --if-not-exists \
                --bootstrap-server kafka:9092

              echo "Creating Kafka topic: Predictions"
              kafka-topics.sh \
                --create \
                --topic Predictions \
                --partitions 1 \
                --replication-factor 1 \
                --if-not-exists \
                --bootstrap-server kafka:9092
              echo "Creating Kafka topic: Metrics"
              kafka-topics.sh \
                --create \
                --topic Metrics \
                --partitions 1 \
                --replication-factor 1 \
                --if-not-exists \
                --bootstrap-server kafka:9092
      containers:
        - name: submit-flink-job
          image: pratulw5/frauddetection-flinkjobs:dev
          imagePullPolicy: Always
          command:
            - bash
            - -c
            - |
              echo 'Waiting for Flink JobManager REST on port 8081...'
              while ! (echo > /dev/tcp/flink-jobmanager/8081) 2>/dev/null; do sleep 2; done

              echo 'Submitting Flink job...'
              flink run -d -m flink-jobmanager:8081 -py /opt/Jobs/Combine.py
