apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  labels:
    app: flink
    component: jobmanager
spec:
  ports:
    - name: web
      port: 8081  # Flink Web UI
      targetPort: 8081
    - name: rpc
      port: 6123  # Flink JobManager RPC
      targetPort: 6123
    - name: blob
      port: 6124  # Ensure this is exposed for BlobServer
      targetPort: 6124
  selector:
    app: flink
    component: jobmanager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  labels:
    app: flink
    component: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: pratulw5/frauddetection-flink:dev
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081  # Flink Web UI
            - containerPort: 6123  # Flink JobManager RPC
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager"
            - name: JOB_MANAGER_RPC_PORT
              value: "6123"
            - name: JOB_MANAGER_WEB_PORT
              value: "8081"
            - name: JOB_MANAGER_BLOB_SERVER_PORT
              value: "6124"  # Set the BlobServer port
            - name: akka.frame-size
              value: "104857600"  # 100 MB frame size
            - name: akka.ask.timeout
              value: "60000"  # Optionally increase timeout
            # Increase frame size settings
            - name: FLINK_AKKA_FRAME_SIZE
              value: "104857600"  # 100 MB
            - name: FLINK_TASKMANAGER_NETTY_MAX_FRAME_SIZE
              value: "52428800"  # 50 MB
            - name: FLINK_AKKA_ASK_TIMEOUT
              value: "60000"  # 60 seconds timeout
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-jobmanager
                jobmanager.rpc.port: 6123
                blob.server.port: 6124
                rest.port: 8081
                taskmanager.numberOfTaskSlots: 2
                akka.framesize: 104857600b
          command: ["/docker-entrypoint.sh"]
          args: ["jobmanager"]
