apiVersion: batch/v1
kind: Job
metadata:
  name: flink-sql-submit
spec:
  template:
    spec:
      containers:
        - name: flink-sql-submit
          image: curlimages/curl:latest
          command:
            - /bin/sh
            - -c
            - |
              curl -X POST "http://flink-sql-gateway:8083/v1/sessions" -H "Content-Type: application/json" -d '{}'
              SESSION_ID=$(curl -s "http://flink-sql-gateway:8083/v1/sessions" | jq -r '.sessionHandle.id')
              curl -X POST "http://flink-sql-gateway:8083/v1/sessions/$SESSION_ID/statements" \
                -H "Content-Type: application/json" \
                -d @- <<EOF
{
  "statement": "CREATE TABLE raw_transactions (accountId STRING, amount DOUBLE, ts TIMESTAMP(3), WATERMARK FOR ts AS ts - INTERVAL '5' SECOND) WITH ('connector' = 'kafka', 'topic' = 'raw-transactions', 'properties.bootstrap.servers' = 'kafka:9092', 'format' = 'json', 'scan.startup.mode' = 'earliest-offset'); CREATE TABLE high_value_transactions (accountId STRING, amount DOUBLE, ts TIMESTAMP(3)) WITH ('connector' = 'kafka', 'topic' = 'high-value-transactions', 'properties.bootstrap.servers' = 'kafka:9092', 'format' = 'json'); INSERT INTO high_value_transactions SELECT accountId, amount, ts FROM raw_transactions WHERE amount > 100000;"
}
EOF
restartPolicy: Never
